services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: starvision-postgres
    environment:
      POSTGRES_DB: starvision
      POSTGRES_USER: starvision_user
      POSTGRES_PASSWORD: starvision_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - starvision-network
    restart: unless-stopped

  # Next.js Application
  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URI=postgresql://starvision_user:starvision_password@postgres:5432/starvision
    container_name: starvision-app
    environment:
      - NODE_ENV=production
      - DATABASE_URI=postgresql://starvision_user:starvision_password@postgres:5432/starvision
      - NEXT_PUBLIC_SERVER_URL=http://localhost:3000
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - starvision-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  starvision-network:
    driver: bridge
