services:
  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starvision-app-prod
    environment:
      - NODE_ENV=production
      - DATABASE_URI=postgresql://${POSTGRES_USER:-starvision_user}:${POSTGRES_PASSWORD}@starvision-postgres-prod:5432/${POSTGRES_DB:-starvision}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./media_data:/app/media
    networks:
      - starvision-network
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  media_data:

networks:
  starvision-network:
    external: true
